export const SPEC_LIST = {
  Body: {
    'Bmep (Brake Mean Effective Pressure)': null,
    'Body Type': null,
    'Boot Capacity': null,
    'Brake System (Foot Brake)': null,
    'Braked Area': null,
    Brakes: null,
    'Chassis Range': null,
    'Chassis Weigth': null,
    'Coach Work': null,
    'Curb Weight': null,
    Dimensions: null,
    Doors: null,
    'Driven Wheels': null,
    'Dry Weight': null,
    Features: null,
    Frame: null,
    'Front Axle': null,
    'Front Brakes': null,
    'Front Brakes - Disc Dimensions': null,
    'Front Rims': null,
    'Front Stabilizer': null,
    'Front Suspension': null,
    'Front Tire': null,
    'Front Track': null,
    'Frontal Area': null,
    'Gross Weight': null,
    'Ground Clearance': null,
    Handling: null,
    Height: null,
    Length: null,
    'Lengthwheelbase Ratio': null,
    'Parking Brake (Hand Brake)': null,
    'Rear Axle': null,
    'Rear Brakes': null,
    'Rear Brakes - Disc Dimensions': null,
    'Rear Rims': null,
    'Rear Stabilizer': null,
    'Rear Suspension': null,
    'Rear Tire': null,
    'Rear Track': null,
    'Seating Capacity': null,
    Segment: null,
    Steering: null,
    'Suspension (Fr/R)': null,
    Tires: null,
    Track: null,
    Tuner: null,
    Weight: null,
    'Weight Distribution': null,
    'Wheel Rims': null,
    Wheelbase: null,
    'Wheelbase / Track (Fr/R)': null,
    Width: null,
    'Width (Excluding Mirrors)': null,
    'Width (Including Mirrors)': null,
  },
  'Energy Efficiency': {
    'Battery Capacity': null,
    'Battery Range': null,
    'Battery Type': null,
    'Battery Voltage': null,
    'Charging Time': null,
    'Co2 Effizienz (De)': null,
    'Co2 Emissions': null,
    'Combined Consumption': null,
    'Consumption (2Nd Engine)': null,
    'Electric Motor': null,
    'Emission Class': null,
    'Emission Law': null,
    'Energy Capacity': null,
    'Energy Source': null,
    'Energy Source (2Nd Engine)': null,
    'Extra-Urban Consumption': null,
    'Fast Charging Capability': null,
    'Fuel Consumption': null,
    'Fuel Tank Capacity': null,
    'Fuel Type': null,
    'High Consumption': null,
    'Ignition System': null,
    'Low Consumption': null,
    'Medium Consumption': null,
    'Miles Per Gallon Consumption': null,
    'Power Consumption': null,
    'Urban Consumption': null,
    'Very High Consumption': null,
  },
  Engine: {
    Aspiration: null,
    Bore: null,
    'Bore And Stroke': null,
    Camshaft: null,
    Capacity: null,
    Catalyst: null,
    'Combustion Principle': null,
    'Compression Ratio': null,
    'Cylinder Block': null,
    'Drive Type': null,
    'Engine Code': null,
    'Engine Construction': null,
    'Engine Coolant': null,
    'Engine Manufacturer': null,
    'Engine Position': null,
    'Engine Type': null,
    'Fuel System': null,
    Ignition: null,
    'Maximum Power': null,
    'Maximum Power Rpm': null,
    'Maximum Rpm': null,
    'Maximum Torque': null,
    'Number Of Engines': null,
    'Power Per Litre': null,
    'Secondary Power': null,
    'Specific Output': null,
    'Specific Torque': null,
    Stroke: null,
    'Torque/Weight': null,
    Turbo: null,
    Valvetrain: null,
  },
  Features: {
    'Front Headroom': null,
    'Front Hip Room': null,
    'Front Legroom': null,
    'Front Shoulder Room': null,
    'Interior Volume': null,
    'Maximum Braked Trailer Mass': null,
    'Maximum Front Axle Mass': null,
    'Maximum Nose Weight': null,
    'Maximum Permissible Mass': null,
    'Maximum Rear Axle Mass': null,
    'Maximum Roof Load': null,
    'Maximum Unbraked Trailer Mass': null,
    Mirrors: null,
    'Rear Headroom': null,
    'Rear Hip Room': null,
    'Rear Legroom': null,
    'Rear Shoulder Room': null,
    'Standard Payload': null,
    'Towing Capacity': null,
    'Turning Circle': null,
  },
  Gearbox: { Clutch: null, 'Top Gear Ratio': null, Transmission: null },
  Performance: {
    '0 To 1000M Duration': null,
    '0 To 120 Kph Duration': null,
    '0 To 130 Kph Duration': null,
    '0 To 140 Kph Duration': null,
    '0 To 160 Kph Duration': null,
    '0 To 180 Kph Duration': null,
    '0 To 220 Kph Duration': null,
    '0 To 240 Kph Duration': null,
    '0 To 250 Kph Duration': null,
    '0 To 300 Kph Duration': null,
    '0 To 40 Kph Duration': null,
    '0 To 400M (1/4 Mile) Duration': null,
    '0 To 50 Kph Duration': null,
    '0 To 60 Kph Duration': null,
    '0 To 80 Km/H Duration': null,
    '0-100 Km/H (0-62 Mph) Duration': null,
    '0-200 Km/H (0-124 Mph) Duration': null,
    '100-0 Km/H (62-0 Mph) Braking Distance': null,
    '200-0 Km/H (124-0 Mph) Braking Distance': null,
    'Dry Weight/Power Ratio': null,
    'Power-To-Weight Ratio': null,
    Redline: null,
    'Top Speed': null,
    'Weight-To-Power Ratio': null,
  },
};
